version: '3'
services:
  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: somepass

  apache:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8081:80'
      - '4443:443'
    volumes:
     - ./websites:/var/www/html
     - ./conf:/etc/apache2/sites-enabled
    environment:
     - ALLOW_OVERRIDE=true

volumes:
  db_data: {}
